#!/usr/bin/env bash
# Bridge script: reads Terraform outputs and generates Ansible inventory
# Usage: ./scripts/terraform-to-ansible.sh [environment]
# Default environment: dev

set -euo pipefail

ENV="${1:-dev}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$PROJECT_ROOT/terraform/environments/$ENV"
INVENTORY_FILE="$PROJECT_ROOT/ansible/inventory/$ENV"

echo "==> Reading Terraform outputs from $TF_DIR"

cd "$TF_DIR"

NGINX_IP=$(terraform output -raw nginx_public_ip 2>/dev/null) || {
    echo "ERROR: Failed to read nginx_public_ip. Did you run 'terraform apply'?"
    exit 1
}

APP_IP=$(terraform output -raw app_private_ip 2>/dev/null) || {
    echo "ERROR: Failed to read app_private_ip. Did you run 'terraform apply'?"
    exit 1
}

echo "    nginx_public_ip = $NGINX_IP"
echo "    app_private_ip  = $APP_IP"

echo "==> Generating Ansible inventory at $INVENTORY_FILE"

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by scripts/terraform-to-ansible.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

[webservers]
nginx ansible_host=$NGINX_IP

[appservers]
app ansible_host=$APP_IP ansible_ssh_common_args='-o ProxyJump=ubuntu@$NGINX_IP'

[$ENV:children]
webservers
appservers
EOF

echo "==> Done. Inventory ready for ansible-playbook."
